name: Deploy static site to cPanel via FTP

on:
  push:
    branches:
      - master   # deploy only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to cPanel with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: ${{ secrets.FTP_TARGET }}
          local-dir: ./          # upload everything in repo root
          protocol: ftps         # try 'ftp' if your host doesn’t support FTPS
          exclude: |
            **/.git*
            **/.github*
            README.md
